name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:

  push:
    branches: [ main ]

  # workflow_dispatch:
  #   inputs:
  #     logLevel:
  #       description: 'Log level'     
  #       required: true
  #       default: 'warning'
  #     tags:
  #       description: 'Test scenario tags' 


# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: ghcr.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: self-hosted


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Deploying stack to Docker Swarm
        run: |
             ls -lh
             git pull
             sudo docker stack deploy -c docker-compose.yml CVAT-main
             rm -rf *

        working-directory: /home/ubuntu/cvat

